# Importing libraries

In [ ]:
import numpy as np
import pandas as pd
import  seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from pandas import read_excel
file_name = '/content/gdrive/MyDrive/GPCR A+X.xlsx' 
df = pd.read_excel(file_name, index_col=0)
#df = pd.read_excel(file_name)
print(df.head()) # print the first 5 rows

            PubchemFP2  PubchemFP3  PubchemFP4  ...  BiGram399  BiGram400  Target
PubchemFP1                                      ...                              
1                    1           0           0  ...     5.0262     1.5291       1
1                    1           1           1  ...     5.0772     1.5490       1
1                    1           0           0  ...     5.0772     1.5490       1
1                    1           1           0  ...     2.7551     1.3303       1
1                    1           1           0  ...     2.7551     1.3303       1

[5 rows x 1281 columns]


In [ ]:
#Split data into independent (X) and dependent(Y) columns

y = df['Target'].values
X = df.drop('Target', axis=1).values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(1488, 1280)
(372, 1280)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[209  25]
 [ 51  87]]


0.7956989247311828

In [ ]:
p = classifier.predict_proba(X_test)[:,1]

In [ ]:
from sklearn.metrics import roc_auc_score
print("AUC = ",roc_auc_score(y_test,p))

AUC =  0.8593150006193484


In [ ]:
from sklearn.metrics import matthews_corrcoef,confusion_matrix
matthews_corrcoef(y_test,y_pred)

0.5513775533303269

In [ ]:
TP = cm[0][0]
TN = cm[1][1]
FP = cm[0][1]
FN = cm[1][0]
print('True Positives:', TP)
print('True Negatives:', TN)
print('False Positives:', FP)
print('False Negatives:', FN)

True Positives: 209
True Negatives: 87
False Positives: 25
False Negatives: 51


In [ ]:
sensitivity=(TP/(TP+FN))
sensitivity

0.8038461538461539

In [ ]:
specificity = (TN/(TN+FP))
specificity

0.7767857142857143

# Applying SHAP

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import shap
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from collections import Counter
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from xgboost import XGBClassifier
from sklearn.utils import shuffle
from imblearn.pipeline import Pipeline
import lightgbm as lgb

The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.


In [ ]:
pip install shap

In [ ]:
features = np.array(df.columns[:-1])
target = 'Target'

In [ ]:
X = df[features]
y = df[target]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df[features], df[target], test_size=0.20, random_state=50)

In [ ]:
def xgb_shap_values(X_train, y_train, X_test):

    model = XGBClassifier()
    model.fit(X_train, y_train)
    explainer = shap.TreeExplainer(model, X_train)
    shap_values_xgb = explainer.shap_values(X_test)
    #shap.summary_plot(shap_values_xgb, X_test,max_display=20)
    #shap.summary_plot(shap_values_xgb, X_test, plot_type ='bar',max_display=20)
    # shap.dependence_plot("Age", shap_values_xgb, X_test, interaction_index = 'rate Po2')
    shap_sum = np.abs(shap_values_xgb).mean(axis=0)
    importance_df = pd.DataFrame([features, shap_sum.tolist()]).T
    importance_df.columns = ['Column Name', 'Shap Importance']
    importance_df= importance_df.sort_values('Shap Importance', ascending = False)
    return importance_df

In [ ]:
selected_df = xgb_shap_values(X_train, y_train,  X_test)

In [ ]:
selected_df = selected_df[0:800]
selected_df

Column Name Shap Importance
887       BiGram8        0.228991
924      BiGram45        0.138555
899      BiGram20        0.126535
527  PubchemFP529        0.112576
964      BiGram85         0.10653
..            ...             ...
313  PubchemFP315               0
312  PubchemFP314               0
311  PubchemFP313               0
310  PubchemFP312               0
309  PubchemFP311               0

[800 rows x 2 columns]

In [ ]:
cols = selected_df['Column Name']
cols

887         BiGram8
924        BiGram45
899        BiGram20
527    PubchemFP529
964        BiGram85
           ...     
313    PubchemFP315
312    PubchemFP314
311    PubchemFP313
310    PubchemFP312
309    PubchemFP311
Name: Column Name, Length: 800, dtype: object

In [ ]:
## converting df to numpy array/list
trainingdf = np.array(cols)
trainingdf

array(['BiGram8', 'BiGram45', 'BiGram20', 'PubchemFP529', 'BiGram85',
       'BiGram305', 'BiGram5', 'BiGram1', 'BiGram283', 'PubchemFP704',
       'BiGram13', 'BiGram145', 'PubchemFP378', 'PubchemFP244',
       'PubchemFP582', 'PubchemFP653', 'PubchemFP668', 'BiGram351',
       'PubchemFP341', 'BiGram70', 'BiGram106', 'PubchemFP380',
       'BiGram25', 'BiGram16', 'BiGram17', 'BiGram34', 'PubchemFP556',
       'BiGram205', 'PubchemFP20', 'PubchemFP567', 'BiGram365',
       'BiGram390', 'BiGram394', 'BiGram193', 'BiGram11', 'BiGram220',
       'BiGram151', 'BiGram110', 'PubchemFP771', 'BiGram357', 'BiGram78',
       'BiGram339', 'BiGram130', 'PubchemFP646', 'PubchemFP680',
       'PubchemFP730', 'BiGram236', 'BiGram358', 'PubchemFP548',
       'BiGram359', 'BiGram65', 'PubchemFP570', 'BiGram231',
       'PubchemFP695', 'BiGram293', 'BiGram71', 'PubchemFP536',
       'BiGram14', 'BiGram273', 'PubchemFP423', 'BiGram154', 'BiGram73',
       'PubchemFP537', 'BiGram137', 'PubchemFP214', 'Bi

In [ ]:
df1 = X[trainingdf]
df1

BiGram8  BiGram45  ...  PubchemFP312  PubchemFP311
PubchemFP1                     ...                            
1            8.1017    3.0698  ...             0             0
1            8.3591    2.8754  ...             0             0
1            8.3591    2.8754  ...             0             0
1            5.5258    2.5326  ...             0             0
1            5.5258    2.5326  ...             0             0
...             ...       ...  ...           ...           ...
1            7.5473    3.1450  ...             0             0
1            7.5473    3.1450  ...             0             0
1            7.5473    3.1450  ...             0             0
1            7.5473    3.1450  ...             0             0
1            7.5473    3.1450  ...             0             0

[1860 rows x 800 columns]

In [ ]:
X = df1.values
y = y.values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 20)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(1488, 800)
(372, 800)


In [ ]:
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from xgboost import XGBClassifier
classifier_shap = XGBClassifier()
classifier_shap.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred1 = classifier_shap.predict(X_test)
cm_shap = confusion_matrix(y_test, y_pred1)
print(cm_shap)
accuracy_score(y_test, y_pred1)

[[217  21]
 [ 41  93]]


0.8333333333333334

# Now we apply Univariate FST

In [ ]:
#Split data into independent (X) and dependent(Y) columns
y = df['Target'].values
X = df.drop('Target', axis=1).values

In [ ]:
from sklearn.feature_selection import SelectKBest,chi2
bestfeatures = SelectKBest(score_func=chi2, k=800)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=20)

In [ ]:
##Normalize the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [ ]:
select = bestfeatures.fit(X_train,y_train)
X_train_selected = select.transform(X_train)

In [ ]:
print("X_train.shape: {}".format(X_train.shape))
print("X_train_selected.shape: {}".format(X_train_selected.shape))

X_train.shape: (1488, 1280)
X_train_selected.shape: (1488, 800)


In [ ]:
mask = select.get_support()
mask

array([False, False,  True, ...,  True,  True,  True])

In [ ]:
select = bestfeatures.fit(X_test,y_test)
X_test_selected = select.transform(X_test)

In [ ]:
print(X_train_selected.shape)
print(X_test_selected.shape)

(1488, 800)
(372, 800)


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train_selected)
X_test = scaler.transform(X_test_selected)

In [ ]:
from xgboost import XGBClassifier
classifier_xgb = XGBClassifier()
classifier_xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_xgb = classifier_xgb.predict(X_test)
cm_xgb = confusion_matrix(y_test, y_pred_xgb)
print(cm_xgb)
accuracy_score(y_test, y_pred_xgb)

[[224  14]
 [116  18]]


0.6505376344086021